CREATE SEQUENCE IF NOT EXISTS cozinha_seq START 1;
CREATE SEQUENCE IF NOT EXISTS restaurante_seq START 1;
CREATE SEQUENCE IF NOT EXISTS cidade_seq START 1;
CREATE SEQUENCE IF NOT EXISTS estado_seq START 1;
CREATE SEQUENCE IF NOT EXISTS produto_seq START 1;
CREATE SEQUENCE IF NOT EXISTS usuario_seq START 1;
CREATE SEQUENCE IF NOT EXISTS grupo_seq START 1;
CREATE SEQUENCE IF NOT EXISTS permissao_seq START 1;